#!/bin/bash
# Displays the default *input* device (microphone), volume, and mute status for i3blocks

set -a

AUDIO_HIGH_SYMBOL=${AUDIO_HIGH_SYMBOL:-'🎙'}
AUDIO_MED_THRESH=${AUDIO_MED_THRESH:-50}
AUDIO_MED_SYMBOL=${AUDIO_MED_SYMBOL:-'🎙'}
AUDIO_LOW_THRESH=${AUDIO_LOW_THRESH:-0}
AUDIO_LOW_SYMBOL=${AUDIO_LOW_SYMBOL:-'🎙'}
AUDIO_MUTED_SYMBOL=${AUDIO_MUTED_SYMBOL:-'🎙'}

AUDIO_DELTA=${AUDIO_DELTA:-5}

DEFAULT_COLOR=${DEFAULT_COLOR:-"#DDDDDD"}
MUTED_COLOR=${MUTED_COLOR:-"#D20000"}

LONG_FORMAT=${LONG_FORMAT:-'${SYMB}: ${VOL}% [${INDEX}:${NAME}]'}
SHORT_FORMAT=${SHORT_FORMAT:-'${SYMB}: ${VOL}%'}
MUTED_FORMAT=${MUTED_FORMAT:-'${SYMB}'}
CURRENT_FORMAT="$SHORT_FORMAT"
FORMAT_FLAG=0

USE_ALSA_NAME=${USE_ALSA_NAME:-1}
USE_DESCRIPTION=${USE_DESCRIPTION:-1}

MIXER=${MIXER:-""}
SCONTROL=${SCONTROL:-""}

if [[ -z "$MIXER" ]] ; then
    MIXER="default"
    if amixer -D pulse info >/dev/null 2>&1 ; then
        MIXER="pulse"
    fi
fi

if [[ -z "$SCONTROL" ]] ; then
    SCONTROL=$(amixer -D "$MIXER" scontrols | sed -n "s/Simple mixer control '\([^']*\)',0/\1/p" | head -n1)
fi

CAPABILITY=$(amixer -D $MIXER get $SCONTROL | sed -n "s/  Capabilities:.*cvolume.*/Capture/p")


function move_sources_to_new_default {
    DEFAULT_SOURCE=$1
    pactl list source-outputs | grep index: | grep -o '[0-9]\+' | while read SRC_OUT
    do
        pacmd move-source-output "$SRC_OUT" "$DEFAULT_SOURCE"
    done
}

function set_default_capture_device_next {
    inc=${1:-1}
    num_devices=$(pactl list sources | grep -c "Source #")
    source_arr=($(pactl list sources | grep "Source #" | grep -o '[0-9]\+'))
    default_source_index=$(pactl list sources short | grep "$(pactl info | grep "Default Source" | cut -d" " -f 3)" | cut -f 1)
    for i in "${!source_arr[@]}"; do
        if [[ "${source_arr[$i]}" = "${default_source_index}" ]]; then
          default_source_index=${source_arr[$(( (i+1) % num_devices ))]}
          break
        fi
    done

    pactl set-default-source "$default_source_index"
    move_sources_to_new_default "$default_source_index"
}

function switch_format {
  if [[ "$CURRENT_FORMAT" == "$LONG_FORMAT" ]]; then
    CURRENT_FORMAT=$SHORT_FORMAT
  elif [[ "$CURRENT_FORMAT" == "$SHORT_FORMAT" ]]; then
    CURRENT_FORMAT="$LONG_FORMAT"
  fi
}

case "$BLOCK_BUTTON" in
    1) switch_format $1 ;;
    2) pactl set-source-mute @DEFAULT_SOURCE@ toggle ;;
    3) set_default_capture_device_next ;;
    4) pactl set-source-volume @DEFAULT_SOURCE@ +$AUDIO_DELTA% ;;
    5) pactl set-source-volume @DEFAULT_SOURCE@ -$AUDIO_DELTA% ;;
esac

function print_format {
    echo "$1" | envsubst '${SYMB}${VOL}${INDEX}${NAME}'
}

function print_block {
    ACTIVE=$(pactl list sources | grep "Source #$(pactl list sources short | grep "$(pactl info | grep "Default Source" | cut -d" " -f 3)" | cut -f 1)" -B1 -A50 | grep "alsa.card \|Description\|Volume: \(front\|mono\)\|Mute:")
    for name in NAME MUTED VOL INDEX; do
        read $name
    done < <(echo "$ACTIVE")
    INDEX=$(echo "$INDEX" | grep -o '[0-9]\+')
    VOL=$(echo "$VOL" | grep -o "[0-9]*%" | head -1 )
    VOL="${VOL%?}"

    NAME=$(echo "$NAME" | sed \
's/.*: \(.*\)/\1/; t;'\
's/.*/unknown/')

    if [[ $USE_ALSA_NAME == 1 ]] ; then
        ALSA_NAME=$(pactl list sources |\
awk '/^\s*\*/{f=1}/^\s*index:/{f=0}f' |\
grep "alsa.name\|alsa.mixer_name" |\
head -n1 |\
sed 's/.*= "\(.*\)".*/\1/')
        NAME=${ALSA_NAME:-$NAME}
    elif [[ $USE_DESCRIPTION == 1 ]] ; then
        DESCRIPTION=$(pactl list sources |\
awk '/^\s*\*/{f=1}/^\s*index:/{f=0}f' |\
grep "device.description" |\
head -n1 |\
sed 's/.*= "\(.*\)".*/\1/')
        NAME=${DESCRIPTION:-$NAME}
    fi

    if [[ $MUTED =~ "no" ]] ; then
        SYMB=$AUDIO_HIGH_SYMBOL
        [[ $VOL -le $AUDIO_MED_THRESH ]] && SYMB=$AUDIO_MED_SYMBOL
        [[ $VOL -le $AUDIO_LOW_THRESH ]] && SYMB=$AUDIO_LOW_SYMBOL
        COLOR=$DEFAULT_COLOR
    else
        SYMB=$AUDIO_MUTED_SYMBOL
        COLOR=$MUTED_COLOR
    fi

    print_format "$CURRENT_FORMAT"
    print_format "$CURRENT_FORMAT"
    echo "$COLOR"
}

print_block
