#!/bin/bash
# Displays the default device, volume, and mute status for i3blocks

set -a

AUDIO_HIGH_SYMBOL=${AUDIO_HIGH_SYMBOL:-''}
AUDIO_MED_THRESH=${AUDIO_MED_THRESH:-50}
AUDIO_MED_SYMBOL=${AUDIO_MED_SYMBOL:-''}
AUDIO_LOW_THRESH=${AUDIO_LOW_THRESH:-0}
AUDIO_LOW_SYMBOL=${AUDIO_LOW_SYMBOL:-''}
AUDIO_MUTED_SYMBOL=${AUDIO_MUTED_SYMBOL:-''}

AUDIO_DELTA=${AUDIO_DELTA:-5}

DEFAULT_COLOR=${DEFAULT_COLOR:-"#DDDDDD"}
MUTED_COLOR=${MUTED_COLOR:-"#D20000"}

LONG_FORMAT=${LONG_FORMAT:-'${SYMB}: ${VOL}% [${INDEX}:${NAME}]'}
SHORT_FORMAT=${SHORT_FORMAT:-'${SYMB}: ${VOL}%'}
MUTED_FORMAT=${MUTED_FORMAT:-'${SYMB}'}
CURRENT_FORMAT="$SHORT_FORMAT"
FORMAT_FLAG=0

USE_ALSA_NAME=${USE_ALSA_NAME:-1}
USE_DESCRIPTION=${USE_DESCRIPTION:-1}

MIXER=${MIXER:-""}
SCONTROL=${SCONTROL:-""}

if [[ -z "$MIXER" ]] ; then
    MIXER="default"
    if amixer -D pulse info >/dev/null 2>&1 ; then
        MIXER="pulse"
    fi
fi

if [[ -z "$SCONTROL" ]] ; then
    SCONTROL=$(amixer -D "$MIXER" scontrols | sed -n "s/Simple mixer control '\([^']*\)',0/\1/p" | head -n1)
fi

CAPABILITY=$(amixer -D $MIXER get $SCONTROL | sed -n "s/  Capabilities:.*cvolume.*/Capture/p")


function move_sinks_to_new_default {
    DEFAULT_SINK=$1
    pactl list sink-inputs short | awk '{print $1}' | while read SINK
    do
        pactl move-sink-input $SINK $DEFAULT_SINK 2>&1 >> /tmp/volume.log
    done
}

function set_default_playback_device_next {
    inc=${1:-1}
    mapfile -t sink_arr < <(pactl list sinks | awk '
      /^Sink #[0-9]+/ {
          if (id != "" && avail == "yes") print id
          id = $2
          sub(/^#/, "", id)
          avail = "no"
          next
      }
      /, not available\)/ {
          avail = "no"
          next
      }
      /, available\)/ {
          avail = "yes"
          next
      }
      /availability unknown/ {
          avail = "yes"
          next
      }
      END {
          if (id != "" && avail == "yes") print id
      }')

    num_devices=${#sink_arr[@]}
    default_sink_index=$(
      pactl list sinks short \
      | awk -v def="$(pactl info | awk -F': ' '/Default Sink/ {print $2}')" '
           $2 == def {print $1}'
    )

    for i in "${!sink_arr[@]}"; do
        if [[ "${sink_arr[$i]}" = "${default_sink_index}" ]]; then
          default_sink_index=${sink_arr[$(($(($i+1))%$num_devices))]}
          break
        fi
    done

    pactl set-default-sink $default_sink_index
    move_sinks_to_new_default $default_sink_index
}

function switch_format {
  if [[ "$CURRENT_FORMAT" == "$LONG_FORMAT" ]]; then
    CURRENT_FORMAT=$SHORT_FORMAT
  elif [[ "$CURRENT_FORMAT" == "$SHORT_FORMAT" ]]; then
    CURRENT_FORMAT="$LONG_FORMAT"
  fi
}

case "$BLOCK_BUTTON" in
    1) switch_format $1 ;;
    2) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
    3) set_default_playback_device_next ;;
    4) pactl set-sink-volume @DEFAULT_SINK@ +$AUDIO_DELTA% ;;
    5) pactl set-sink-volume @DEFAULT_SINK@ -$AUDIO_DELTA% ;;
esac

function print_format {
    echo "$1" | envsubst '${SYMB}${VOL}${INDEX}${NAME}'
}

function print_block {
    ACTIVE=$(pactl list sinks | grep "Sink #$(pactl list sinks short | grep $(pactl info | grep "Default Sink" | cut -d" " -f 3) | cut -f 1)" -B1 -A50 | grep "alsa.card \|Description\|Volume: \(front\|mono\)\|Mute:")
    for name in NAME MUTED VOL INDEX; do
        read $name
    done < <(echo "$ACTIVE")
    INDEX=$(echo "$INDEX" | grep -o '[0-9]\+')
    VOL=$(echo "$VOL" | grep -o "[0-9]*%" | head -1 )
    VOL="${VOL%?}"

    NAME=$(echo "$NAME" | sed \
's/.*: \(.*\)/\1/; t;'\
's/.*/unknown/')

    if [[ $USE_ALSA_NAME == 1 ]] ; then
        ALSA_NAME=$(pactl list sinks |\
awk '/^\s*\*/{f=1}/^\s*index:/{f=0}f' |\
grep "alsa.name\|alsa.mixer_name" |\
head -n1 |\
sed 's/.*= "\(.*\)".*/\1/')
        NAME=${ALSA_NAME:-$NAME}
    elif [[ $USE_DESCRIPTION == 1 ]] ; then
        DESCRIPTION=$(pactl list sinks |\
awk '/^\s*\*/{f=1}/^\s*index:/{f=0}f' |\
grep "device.description" |\
head -n1 |\
sed 's/.*= "\(.*\)".*/\1/')
        NAME=${DESCRIPTION:-$NAME}
    fi

    if [[ $MUTED =~ "no" ]] ; then
        SYMB=$AUDIO_HIGH_SYMBOL
        [[ $VOL -le $AUDIO_MED_THRESH ]] && SYMB=$AUDIO_MED_SYMBOL
        [[ $VOL -le $AUDIO_LOW_THRESH ]] && SYMB=$AUDIO_LOW_SYMBOL
        COLOR=$DEFAULT_COLOR
    else
        SYMB=$AUDIO_MUTED_SYMBOL
        COLOR=$MUTED_COLOR
    fi

    print_format "$CURRENT_FORMAT"
    print_format "$CURRENT_FORMAT"
    echo "$COLOR"
}

print_block
